#ex3.1
fruits=["apple","banana","cherry"]
print(fruits[1])
#ex3.2
fruits=["apple","banana","cherry"]
fruits[0]="kiwi"
#ex3.3
fruits=["apple","banana","cherry"]
fruits.append("orange")
#ex3.4
fruits=["apple","banana","cherry"]
fruits.insert(1,"lemon")
#ex3.5
fruits=["apple","banana","cherry"]
fruits.remove("banana")
#ex3.6
fruits=["apple","banana","Cherry"]
print(fruits[-1])
#ex3.7
fruits=["apple","banana","cherry","orange","kiwi","melon","mango"]
print(fruits[2:5])
#ex3.8
fruits=["apple","banana","cherry"]
print(len(fruits))
